// <auto-generated />
using Meridian.DataAccess.PdP;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meridian.DataAccess.Migrations.Policy
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260803211501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Meridian.DataAccess.Models.AmountLimitConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Key");

                    b.ToTable("AmountLimits");

                    b.HasData(
                        new
                        {
                            Key = "expense.approve.manager_limit",
                            Value = 5000m
                        });
                });

            modelBuilder.Entity("Meridian.DataAccess.Models.ManagerOf", b =>
                {
                    b.Property<string>("ManagerUserId")
                        .HasColumnType("text");

                    b.Property<string>("ReportUserId")
                        .HasColumnType("text");

                    b.HasKey("ManagerUserId", "ReportUserId");

                    b.ToTable("ManagerOfs");

                    b.HasData(
                        new
                        {
                            ManagerUserId = "u-nadia",
                            ReportUserId = "u-emma"
                        },
                        new
                        {
                            ManagerUserId = "u-nadia",
                            ReportUserId = "u-mateo"
                        });
                });

            modelBuilder.Entity("Meridian.DataAccess.Models.RoleAssignment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("RoleAssignments");

                    b.HasData(
                        new
                        {
                            UserId = "u-emma",
                            Department = "Sales",
                            Role = "employee"
                        },
                        new
                        {
                            UserId = "u-mateo",
                            Department = "Sales",
                            Role = "employee"
                        },
                        new
                        {
                            UserId = "u-nadia",
                            Department = "Sales",
                            Role = "manager"
                        },
                        new
                        {
                            UserId = "u-finn",
                            Department = "Finance",
                            Role = "finance"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
