<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AuthZen.Pep</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
	  <PackageReference Include="Duende.AccessTokenManagement" />
	  <ProjectReference Include="..\AuthZen.Contracts\AuthZen.Contracts.csproj" />
  </ItemGroup>
</Project>
